#!/usr/bin/env node
/**
 * prebuild.mjs
 *
 * Compiles grammar.peggy → grammar.gen.ts before TypeScript compilation.
 * This embeds the parser as a compiled JS function, removing the runtime
 * dependency on reading the .peggy file from disk.
 *
 * Run automatically via "npm run build" (prebuild hook).
 */

import { readFileSync, writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import peggy from 'peggy'

const __dirname = dirname(fileURLToPath(import.meta.url))
const grammarPath = join(__dirname, 'src/parser/grammar.peggy')
const outputPath  = join(__dirname, 'src/parser/grammar.gen.ts')

const grammar = readFileSync(grammarPath, 'utf-8')

// Compile the grammar to a bare parser function (no module wrapper).
// We'll export it as a named export from the generated TS file.
const parserSource = peggy.generate(grammar, {
  output: 'source',
  format: 'bare',
})

// Wrap in a typed TS module
const tsModule = `// AUTO-GENERATED by prebuild.mjs — do not edit manually.
// Source: src/parser/grammar.peggy
// Regenerate with: npm run prebuild

/* eslint-disable */
// @ts-nocheck

const _parserSource = ${JSON.stringify(parserSource)};

// We evaluate the parser source so it runs in the current module scope.
// This is equivalent to peggy.generate(grammar, { output: 'parser' }) but
// avoids a runtime dependency on the .peggy file or the peggy library.
function makeParser() {
  // peggy "bare" format outputs a function body — wrap it in a factory
  const fn = new Function('return (' + _parserSource + ')')
  return fn()
}

export const compiledParser = makeParser()
`

writeFileSync(outputPath, tsModule, 'utf-8')
console.log(`✓ Compiled grammar.peggy → src/parser/grammar.gen.ts`)
